In [14]:
import pandas as  pd

In [3]:
df = pd.read_csv('kiva_el.csv')
df.head(2)

,LocationName,ISO,country,region,world_region,MPI,geo,lat,lon,id,...,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date,year,month,day
0,"Ahuachapan, El Salvador",SLV,El Salvador,Ahuachapan,Latin America and Caribbean,0.03,"(13.8216148, -89.9253233)",13.821615,-89.925323,670484,...,2014-02-21 20:41:13+00:00,14.0,29,NaN,"female, female, female",bullet,2014-02-15,2014,February,Saturday
1,"Ahuachapan, El Salvador",SLV,El Salvador,Ahuachapan,Latin America and Caribbean,0.03,"(13.8216148, -89.9253233)",13.821615,-89.925323,675795,...,NaN,14.0,53,"#Animals, #Parent, #Supporting Family, user_fa...","male, male, male",bullet,2014-02-24,2014,February,Monday

In [4]:
df.region.unique()

array(['Ahuachapan', 'La Libertad', 'San Miguel', 'San Vicente',
       'Santa Ana', 'Sonsonate'], dtype=object)

In [7]:
df = df[df.country == 'USA']
df.head()

Empty DataFrame
Columns: [LocationName, ISO, country, region, world_region, MPI, geo, lat, lon, id, funded_amount, loan_amount, activity, sector, use, country_code, currency, partner_id, posted_time, disbursed_time, funded_time, term_in_months, lender_count, tags, borrower_genders, repayment_interval, date, year, month, day]
Index: []

[0 rows x 30 columns]

In [6]:
df.sample(500).to_csv('kiva.csv')

(500, 30)

In [15]:
df = pd.read_csv('kiva5.csv')
df

,Unnamed: 0,LocationName,ISO,country,region,world_region,MPI,geo,lat,lon,...,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date,year,month,day
0,1750,"San Miguel, El Salvador",SLV,El Salvador,San Miguel,Latin America and Caribbean,0.03,"(13.4792922, -88.1779182)",13.479292,-88.177918,...,2016-07-21 20:33:37+00:00,17.0,17,"#Repeat Borrower, #Parent, #Single Parent, #Wo...",female,monthly,2016-06-18,2016,June,Saturday
1,2816,"San Vicente, El Salvador",SLV,El Salvador,San Vicente,Latin America and Caribbean,0.02,"(13.6390979, -88.7830612)",13.639098,-88.783061,...,2015-09-30 11:07:34+00:00,14.0,7,NaN,female,monthly,2015-09-24,2015,September,Thursday
2,1626,"San Miguel, El Salvador",SLV,El Salvador,San Miguel,Latin America and Caribbean,0.03,"(13.4792922, -88.1779182)",13.479292,-88.177918,...,2016-04-29 09:41:07+00:00,20.0,36,"#Elderly, #Repeat Borrower, #Woman Owned Biz",female,monthly,2016-03-29,2016,March,Tuesday
3,2722,"San Miguel, El Salvador",SLV,El Salvador,San Miguel,Latin America and Caribbean,0.03,"(13.4792922, -88.1779182)",13.479292,-88.177918,...,NaN,14.0,0,#Parent,male,monthly,2017-06-29,2017,June,Thursday
4,2228,"San Miguel, El Salvador",SLV,El Salvador,San Miguel,Latin America and Caribbean,0.03,"(13.4792922, -88.1779182)",13.479292,-88.177918,...,2017-01-09 15:33:46+00:00,14.0,9,#Parent,male,monthly,2017-01-04,2017,January,Wednesday